### ISSUE TITLE
should have docs how to set up monitoring

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-k8s#46]
so that we can  monitor k8s and all the running services

**Comment by hoatle** [comment]
ref: https://sysdig.com/blog/kubernetes-monitoring-prometheus/

**Comment by hoatle** [comment]
related: https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-usage-metering

**Comment by hoatle** [comment]
related: https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/

**Comment by hieptranquoc** [comment]
I confirm it works well
