### ISSUE TITLE
should add teracy-dev-certs >= 0.4.0 dependency and update cert-manager docs

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-k8s#77]
- update dependency
- configure:
  + disable cert generation
  + enable pkcs1 generation (so that we don't have to generate it manually https://github.com/teracyhq-incubator/teracy-dev-k8s/blob/develop/docs/cert-manager.md#use-the-generated-key-pair-from-teracy-dev-certs-to-create-a-ca-issuer)
- update docs/cert-manager to remove the manual step of generating pkcs1 format

**Comment by hoatle** [comment]
@hieptranquoc make sure to verify and confirm the changes.

**Comment by hieptranquoc** [comment]
I confirm it works well
